[[main]]
  identifier = "blogs"
  name = "Blogs"
  url = "blogs"
  weight = 1

[[main]]
  identifier = "solutions"
  name = "Solutions"
  url = "solutions"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 4